<?php

namespace PuntoVenta\PuntoVentaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriaRepository extends EntityRepository
{
	public function getCategoriasByNombre(){		
			$repository = $this->getEntityManager();
		
			return $repository->createQueryBuilder()
			->select('c')
			->from('PuntoVentaBundle:Categoria', 'c')
			->orderBy('c.nombre', 'ASC');
	}
}
