<?php

namespace PuntoVenta\PuntoVentaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ClienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClienteRepository extends EntityRepository
{
	public function getDefaultCliente(){
        return $this->getEntityManager()->createQueryBuilder()
                    ->select('c')
                    ->from('PuntoVentaBundle:Cliente', 'c')
                    ->where('c.nombre = :nombre')
                    ->setParameter('nombre', "Publico General");
    }
}
