parameters:
#    punto_venta_punto_venta.example.class: PuntoVenta\PuntoVentaBundle\Example

services:
#    punto_venta_punto_venta.example:
#        class: %punto_venta_punto_venta.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
