categoria:
    pattern:  /
    defaults: { _controller: "PuntoVentaBundle:Categoria:index" }

categoria_show:
    pattern:  /{id}/show
    defaults: { _controller: "PuntoVentaBundle:Categoria:show" }

categoria_new:
    pattern:  /new
    defaults: { _controller: "PuntoVentaBundle:Categoria:new" }

categoria_create:
    pattern:  /create
    defaults: { _controller: "PuntoVentaBundle:Categoria:create" }
    requirements:  
        _method: post 

categoria_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "PuntoVentaBundle:Categoria:edit" }

categoria_update:
    pattern:  /{id}/update
    defaults: { _controller: "PuntoVentaBundle:Categoria:update" }
    requirements:  
        _method: post|put 

categoria_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "PuntoVentaBundle:Categoria:delete" }


     
