cliente:
    pattern:  /
    defaults: { _controller: "PuntoVentaBundle:Cliente:index" }

cliente_show:
    pattern:  /{id}/show
    defaults: { _controller: "PuntoVentaBundle:Cliente:show" }

cliente_new:
    pattern:  /new
    defaults: { _controller: "PuntoVentaBundle:Cliente:new" }

cliente_create:
    pattern:  /create
    defaults: { _controller: "PuntoVentaBundle:Cliente:create" }
    requirements: { _method: post }

cliente_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "PuntoVentaBundle:Cliente:edit" }

cliente_buscar:
    pattern: /search
    defaults: { _controller: "PuntoVentaBundle:Cliente:search" }
    requirements: { _method: post|put }

cliente_update:
    pattern:  /{id}/update
    defaults: { _controller: "PuntoVentaBundle:Cliente:update" }
    requirements: { _method: post|put }

cliente_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "PuntoVentaBundle:Cliente:delete" }
    requirements: { _method: post|delete }
